### PR TITLE
Revert "Refactor appendtone signature"

### PR DESCRIPTION
**Pull request by datajerk**
Reverts datajerk/c2t#6

Tests failed.

### CODE REVIEW

**Comment by datajerk** [comment]
LOAD ERRERR just getting started.

**Comment by raphlinus** [comment]
I'm trying to install a test environment so I can run these myself. Test failure was not expected, I'm curious what went wrong.

**Comment by datajerk** [comment]
Error happens immediately when trying to load the standard 1333 bps protocol, ERR is from the ROM.  I do not have the time to compare waveforms of working vs. non-working until later tonight.

**Comment by raphlinus** [comment]
Yeah, I've got it figured out, the `dsk` path sets the rate to 48000 but that happens after `outbuf_init`, so the rates mismatched. I've got it working locally.

**Comment by datajerk** [comment]
did you want to send a new PR?

**Comment by raphlinus** [comment]
Yes, I'll send it now.

**Pull request merged**
