### PR TITLE
Fix build modern debian

### PR DESCRIPTION
**Pull request by jepler**
Hi! I found several problems that prevented c2t from building on modern debian.

After these changes, I successfully generated my own .wav file and used it to image a floppy on my //e.

Please let me know if you're interested in me adding github "actions" to test that the software builds properly and possibly even to create downloadable executable files of c2t. Doing this is "fun" (to me) and many projects find it helpful.

### CODE REVIEW

**Comment by datajerk** [comment]
I'll try to get this merged/test within the next week.

**Comment by datajerk** [comment]
Completely forgot about this.  These changes may break how I currently build on MacOS since I'm still using an older version of cl65.  I've not had the time to upgrade to newer versions and then fix all the assembly.

The README states:

Prerequisites:

- `cl65` version 2.13.3 (<https://github.com/mrdudz/cc65-old/raw/master/cc65-sources-2.13.3.tar.bz2>)

I'd suggest for now until I have time to update the assembly (unless your patch fixes all the assembly for the latest version of cl65 (I'll test in about two weeks)) to build the older cl65.

Yes interested in automated build/test/binaries.  However my system test code required Virtual ][ for the mac (its the only emulator I've found that can be automated and works with all the c2t audio waveforms).

**Comment by jepler** [comment]
I've updated this PR with a variant that seems to work on 2.13.3 as well as 2.18.

**Comment by jepler** [comment]
This has become a bit of a grab bag. Please let me know if you'd like me to break it down into multiple PRs.

**Comment by datajerk** [comment]
I've been slammed with other work and again didnt follow up on this.  if you want to submit separate PRs i'll review this month.

**Pull request closed without merging**
